#!/usr/bin/env python
"""Things to be done after project generation.
"""
# Note: it is vital this file *not* have a name ending in .py.
#  If it does, it will break under uwsgi, because sys.executable will be
#  "uwsgi" rather than "python", and this is manifestly not a uwsgi
#  configuration file.


def usage():
    """Show what else the user needs to do.
    """
    print("Next steps (feel free to copy and paste the four-space-indented " +
          "lines):\n")
    print("    cd sqre-uservice-{{ cookiecutter.svc_name}}")
    print("    git init\n")
    print("  Create a Python 3 virtualenv from requirements.txt.")
    print("  (if virtualenvwrapper is installed, that's:\n")
    print("    mkvirtualenv -r requirements.txt -p $(which python3) " +
          "{{ cookiecutter.svc_name }}\n")
    print("  and if it isn't installed, that'll give you an error and you'll")
    print("  need to make a virtualenv the way you prefer.)\n")
    print("    python setup.py develop\n")
    print("  Add your service logic to " +
          "uservice_{{cookiecutter.svc_name}}/server.py.")
    print("  Edit README.md to document your service.")
    print("  Get it working and tested.")
    print("  Tell SQuaRE it's ready for incorporation into api.lsst.codes.")


if __name__ == "__main__":
    usage()
